### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by hg6a6** [reach2sbera/ldct_nonlocal#1]
The URL of the LDCT dataset you provided is not the same as the dataset you used.Can you share your dataset? Or can you tell how it was obtained?

**Comment by reach2sbera** [comment]
In 2019 I mailed the mayo clinic after filling a data-sharing agreement. Upon verifying the agreement form they shared a private link to download the data from their server.  But now it looks like the Low Dose CT Grand Challenge dataset is no longer available. However a large low dose CT dataset by Mayo Clinic is available for download, you can use that.
