### ISSUE TITLE
how I can download LDCT dataset

### ISSUE THREAD

**Issue by chenjiachengzzz** [reach2sbera/ldct_nonlocal#2]
can you tell me how I can download LDCT dataset.

**Comment by reach2sbera** [comment]
In 2019 I mailed the mayo clinic after filling a data-sharing agreement. Upon verifying the agreement form they shared a private link to download the data from their server. But now it looks like the Low Dose CT Grand Challenge dataset is no longer available. However a large low dose CT dataset by Mayo Clinic is available for download, you can use that.
Check the following link : https://wiki.cancerimagingarchive.net/plugins/servlet/mobile?contentId=52758026#content/view/52758026

**Comment by chenjiachengzzz** [comment]
Thank you very much, it helped me a lot!
