### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'image_size'

### ISSUE THREAD

**Issue by sbajh123** [reach2sbera/ldct_nonlocal#5]
When I ran train_model.py, I got this error **_TypeError: __init__() missing 1 required positional argument:'image_size'_**, is there anyone who has solved this problem? thanks

**Comment by sbajh123** [comment]
this is train_model.py
import argparse
from loader import get_loader
from networks import UNet, ImageDiscriminator
from loss import SNDisLoss, SNGenLoss, NCMSE
import torch
import time

parser = argparse.ArgumentParser()

parser.add_argument('--mode', type=str, default='train')
parser.add_argument('--load_mode', type=int, default=0)
parser.add_argument('--data_path', type=str, default='./data/')
parser.add_argument('--saved_path', type=str, default='./npy_img/')
parser.add_argument('--save_path', type=str, default='./save/')
parser.add_argument('--test_patient', type=str, default='L506')

parser.add_argument('--norm_range_min', type=float, default=-1024.0)
parser.add_argument('--norm_range_max', type=float, default=3072.0)
parser.add_argument('--trunc_min', type=float, default=-160.0)
parser.add_argument('--trunc_max', type=float, default=240.0)

parser.add_argument('--transform', type=bool, default=False)
# if patch training, batch size is (--patch_n * --batch_size)
parser.add_argument('--patch_n', type=int, default=10)
parser.add_argument('--patch_size', type=int, default=64)
parser.add_argument('--batch_size', type=int, default=10)

parser.add_argument('--num_epochs', type=int, default=0)
parser.add_argument('--print_iters', type=int, default=5)
parser.add_argument('--decay_iters', type=int, default=30)
parser.add_argument('--save_iters', type=int, default=10)
parser.add_argument('--test_iters', type=int, default=10)

parser.add_argument('--lr', type=float, default=1e-3)

parser.add_argument('--device', type=str)
parser.add_argument('--num_workers', type=int, default=0)
parser.add_argument('--multi_gpu', type=bool, default=False)
parser.add_argument('--load_chkpt', type=bool, default=False)

args = parser.parse_args()

data_loader = get_loader(mode=args.mode,
                         load_mode=args.load_mode,
                         saved_path=args.saved_path,
                         test_patient=args.test_patient,
                         patch_n=(args.patch_n if args.mode=='train' else None),
                         patch_size=(args.patch_size if args.mode=='train' else None),
                         transform=args.transform,
                         batch_size=(args.batch_size if args.mode=='train' else 1),
                         num_workers=args.num_workers)


if args.load_chkpt:
    print('Loading Chekpoint')
    whole_model = torch.load(args.save_path+ 'latest_ckpt.pth.tar')
    netG_state_dict,optG_state_dict = whole_model['netG_state_dict'], whole_model['optG_state_dict']
    netD_state_dict,optD_state_dict = whole_model['netD_state_dict'], whole_model['optD_state_dict']
    netG = UNet()
    netG = netG.cuda()
    netD= ImageDiscriminator()
    netD=netD.cuda()
    optG = torch.optim.Adam(netG.parameters())
    optD= torch.optim.Adam(netD.parameters())
    netD.load_state_dict(netD_state_dict)
    netG.load_state_dict(netG_state_dict)
    optG.load_state_dict(optG_state_dict)
    optD.load_state_dict(optD_state_dict)
    cur_epoch = whole_model['epoch']
    total_iters = whole_model['total_iters']
    lr = whole_model['lr']
   # netG = torch.nn.DataParallel(netG, device_ids=[0, 1])
   # netD = torch.nn.DataParallel(netD, device_ids=[0, 1])
    print(cur_epoch)
else:
    print('Training model from scrath')
    netG = UNet()
    netG = netG.cuda()
    netD= ImageDiscriminator()
    netD=netD.cuda()
    optG = torch.optim.Adam(netG.parameters(), lr=args.lr)
    optD = torch.optim.Adam(netD.parameters(), lr=4*args.lr)
    cur_epoch = 0
    total_iters = 0
    lr=args.lr
    
train_losses = []
criterion= NCMSE()
GANLoss=SNGenLoss()
DLoss=SNDisLoss()
criterion = criterion.cuda()
start_time = time.time()
for epoch in range(cur_epoch, args.num_epochs):
    netG.train()
    for iter_, (x, y) in enumerate(data_loader):
        total_iters += 1

        # add 1 channel
        x = x.unsqueeze(0).float()
        y = y.unsqueeze(0).float()
        if args.patch_size:     #patch training
            x = x.view(-1, 1, args.patch_size, args.patch_size)
            y = y.view(-1, 1, args.patch_size, args.patch_size)

        x = x.cuda()
        y = y.cuda()

        pred = netG(x)
        
        optD.zero_grad(),
        netD.zero_grad(),
        

        pos_neg_imgs = torch.cat([y, pred], dim=0)
        pred_pos_neg = netD(pos_neg_imgs)
        pred_pos, pred_neg = torch.chunk(pred_pos_neg, 2, dim=0)
        d_loss = DLoss(pred_pos, pred_neg)
        d_loss.backward(retain_graph=True)
        optD.step()   
        
        optG.zero_grad()
        netG.zero_grad()
        
        g_loss = GANLoss(pred_neg)
        rloss= criterion(pred, y, x)
        loss =  g_loss + 0.1*rloss   
    
        loss.backward()
            
        optG.step()
            
        # print
        if total_iters % args.print_iters == 0:
            print("STEP [{}], EPOCH [{}/{}], ITER [{}/{}] \nR_LOSS: {:.8f}, G_LOSS: {:.8f}, D_LOSS: {:.14f}, TIME: {:.1f}s".format(total_iters, epoch, 
                                                                                                        args.num_epochs, iter_+1, 
                                                                                                        len(data_loader), rloss.item(), g_loss.item(), d_loss.item()
                                                                                                        ,time.time() - start_time))
        if total_iters % args.decay_iters == 0:
            lr = lr * 0.5
            for param_group in optG.param_groups:
                param_group['lr'] = lr
            for param_group in optD.param_groups:
                param_group['lr'] = 4*lr
        # save model
        if total_iters % args.save_iters == 0:
            saved_model = {
                   'epoch': epoch ,
                   'netG_state_dict': netG.state_dict(),
                   'optG_state_dict': optG.state_dict(),
                   'netD_state_dict': netD.state_dict(),
                   'optD_state_dict': optD.state_dict(),
                   'lr': lr,
                   'total_iters': total_iters
                   }
            torch.save(saved_model, '{}iter_{}_ckpt.pth.tar'.format(args.save_path, total_iters))
            torch.save(saved_model, '{}latest_ckpt.pth.tar'.format(args.save_path))

**Comment by sbajh123** [comment]
this is networks.py
import torch.nn as nn
import torch
import torch.nn.functional as F
from math import exp
from torch.autograd import Variable
import numpy as np


def create_mask(neighborhood_size, SIZE):
    mask=torch.zeros([SIZE,SIZE], dtype=torch.bool)
    for j in range(0,SIZE):
        for i in range(0,int(neighborhood_size*np.sqrt(SIZE)),int(np.sqrt(SIZE))):
            for k in range(neighborhood_size):
                mask[j,i+k]=1
    return mask
    
class NonLocal(nn.Module):
    """ Self attention Layer"""
    def __init__(self,in_dim,activation, SIZE):
        super(NonLocal,self).__init__()
        self.chanel_in = in_dim
        self.activation = activation
        
        self.query_conv = nn.Conv2d(in_channels = in_dim , out_channels = in_dim//8 , kernel_size= 1)
        self.key_conv = nn.Conv2d(in_channels = in_dim , out_channels = in_dim//8 , kernel_size= 1)
        self.value_conv = nn.Sequential(nn.Conv2d(in_channels = in_dim , out_channels = in_dim , kernel_size= 3,padding=1 ),
                                        nn.ReLU(inplace=True),
                                        nn.Conv2d(in_channels = in_dim , out_channels = in_dim , kernel_size= 3,padding=1 ))            
        #self.gamma = nn.Parameter(torch.zeros(1))

        self.softmax  = nn.Softmax(dim=-1) #
        self.SIZE=int(SIZE)
        self.neighborhood_size=3
        #self.n_neighbour=9
        self.mask=create_mask(self.neighborhood_size, self.SIZE)
        self.relu=nn.ReLU(inplace=True)
    def forward(self,x):
        """
            inputs :
                x : input feature maps( B X C X W X H)
            returns :
                out : self attention value + input feature 
                attention: B X N X N (N is Width*Height)
        """
        m_batchsize,C,width ,height = x.size()
        proj_query  = self.query_conv(x).view(m_batchsize,-1,width*height).permute(0,2,1) # B X CX(N)
        proj_key =  self.key_conv(x).view(m_batchsize,-1,width*height) # B X C x (*W*H)
        energy =  torch.bmm(proj_query,proj_key) # transpose check
        #
        mask=self.mask.repeat(m_batchsize,1,1)
    
        energy[~mask]=0
        

        attention = self.softmax(energy) # BX (N) X (N) 
        proj_value = self.value_conv(x).view(m_batchsize,-1,width*height) # B X C X N


        out = torch.bmm(proj_value,attention.permute(0,2,1) )
        out = out.view(m_batchsize,C,width,height)
    

        return torch.cat((out,x),dim=1)
      



class UNet(nn.Module):
    
  def __init__(self, image_size):
    super(UNet, self).__init__()   
    self.input_channel=1
    self.inter_channel=64
    self.conv1=nn.Sequential(nn.Conv2d(1,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True))
    self.layer1=nn.Sequential(nn.Conv2d(self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True),
                             nn.Conv2d(self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True),
                             nn.Conv2d(self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True))
    self.pool1=nn.MaxPool2d(kernel_size=(2, 2))
    self.layer2=nn.Sequential(nn.Conv2d(self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True),
                             nn.Conv2d(self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True),
                             nn.Conv2d(self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True))
    self.pool2=nn.MaxPool2d(kernel_size=(2, 2))
    self.layer3=nn.Sequential(NonLocal(64, 'relu', (image_size/4)*(image_size/4)),
		 	                      nn.Conv2d(2*self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True),
       			               NonLocal(64, 'relu', image_size/4*(image_size/4)),
                             nn.Conv2d(2*self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True),                
                             NonLocal(64, 'relu', image_size/4*(image_size/4)),
                             nn.Conv2d(2*self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True), 
                             NonLocal(64, 'relu', image_size/4*(image_size/4)),
                             nn.Conv2d(2*self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True))
    self.pool3=nn.Upsample(scale_factor=2, mode='nearest')
    self.layer4=nn.Sequential(nn.Conv2d(2*self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True),
                             nn.Conv2d(self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True),
                             nn.Conv2d(self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True))
    self.pool4=nn.Upsample(scale_factor=2, mode='nearest')    
    
    self.layer5=nn.Sequential(nn.Conv2d(2*self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True),
                             nn.Conv2d(self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True),
                             nn.Conv2d(self.inter_channel,self.inter_channel,5,padding=2),
                             nn.ReLU(inplace=True))
    self.conv2=nn.Conv2d(self.inter_channel,1,3,padding=1)

  def forward(self,x):

      x=self.conv1(x)

      x1=self.layer1(x)

      x=self.pool1(x1)

      x2=self.layer2(x)

      x=self.pool2(x2)

      x=self.layer3(x)

      x=self.pool3(x)

      x=self.layer4(torch.cat((x2 , x),1))

      x=self.pool4(x)

      x=self.layer5(torch.cat((x1 , x),1))

      x=self.conv2(x)
      return x



class SNConvWithActivation(torch.nn.Module):
    """
    SN convolution for spetral normalization conv
    """
    def __init__(self, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, activation=torch.nn.LeakyReLU(0.2, inplace=True)):
        super(SNConvWithActivation, self).__init__()
        self.conv2d = torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding, dilation, groups, bias)
        self.conv2d = torch.nn.utils.spectral_norm(self.conv2d)
        self.activation = activation
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight)
    def forward(self, input):
        x = self.conv2d(input)
        if self.activation is not None:
            return self.activation(x)
        else:
            return x

class Self_Attn(nn.Module):
    """ Self attention Layer"""
    def __init__(self,in_dim):
        super(Self_Attn,self).__init__()
        self.chanel_in = in_dim
        
        self.query_conv = nn.Conv2d(in_channels = in_dim , out_channels = in_dim//8 , kernel_size= 1)
        self.key_conv = nn.Conv2d(in_channels = in_dim , out_channels = in_dim//8 , kernel_size= 1)
        self.value_conv = nn.Conv2d(in_channels = in_dim , out_channels = in_dim , kernel_size= 1)
        self.gamma = nn.Parameter(torch.zeros(1))

        self.softmax  = nn.Softmax(dim=-1) #
    def forward(self,x):
        """
            inputs :
                x : input feature maps( B X C X W X H)
            returns :
                out : self attention value + input feature 
                attention: B X N X N (N is Width*Height)
        """
        m_batchsize,C,width ,height = x.size()
        proj_query  = self.query_conv(x).view(m_batchsize,-1,width*height).permute(0,2,1) # B X CX(N)
        proj_key =  self.key_conv(x).view(m_batchsize,-1,width*height) # B X C x (*W*H)
        energy =  torch.bmm(proj_query,proj_key) # transpose check
        attention = self.softmax(energy) # BX (N) X (N) 
        proj_value = self.value_conv(x).view(m_batchsize,-1,width*height) # B X C X N

        out = torch.bmm(proj_value,attention.permute(0,2,1))
        out = out.view(m_batchsize,C,width,height)
        
        out = self.gamma*out + x
        return out
    

        
class ImageDiscriminator(nn.Module):
    def __init__(self):
        super(ImageDiscriminator, self).__init__()
        cnum = 32
        self.discriminator_net = nn.Sequential(
            SNConvWithActivation(1, cnum, 3, 1),
            SNConvWithActivation(cnum, 2*cnum, 3, 2),
            SNConvWithActivation(2*cnum, 4*cnum, 3, 1),
            SNConvWithActivation(4*cnum, 8*cnum, 3, 1),
            SNConvWithActivation(8*cnum, 8*cnum, 3, 2, padding=2),
            SNConvWithActivation(8*cnum, 8*cnum, 3, padding=2),
            SNConvWithActivation(8*cnum, 8*cnum, 3, padding =2),
            Self_Attn(8*cnum),
            SNConvWithActivation(8*cnum, 8*cnum, 3, padding=2),
            Self_Attn(8*cnum),
            SNConvWithActivation(8*cnum, 8*cnum, 3, padding=2)
        )
    def forward(self, input):
        x = self.discriminator_net(input)
        x = x.view((x.size(0),-1))
        return x

**Comment by fightinggirl0** [comment]
I'm also reproducing this network. Can I add your wechat to communicate？

**Comment by sbajh123** [comment]
> 我也在复制这个网络。我可以添加您的微信进行通信吗？

You have encountered the same error

**Comment by fightinggirl0** [comment]
> > 我也在复制这个网络。我可以添加您的微信进行通信吗？
> 
> You have encountered the same error

yep

**Comment by sbajh123** [comment]
> > > 我也在复制这个网络。我可以添加您的微信进行通信吗？
> > 
> > 
> > You have encountered the same error
> 
> yep

wechat: haooo996
